### PR TITLE
fix windows encoding

### PR DESCRIPTION
**Pull request by trim21**
```text
        File "C:\Users\Trim21\proj\furo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Trim21\proj\furo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Trim21\proj\furo\.venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "C:\Users\Trim21\AppData\Local\Temp\pip-build-env-mz9nqtpo\overlay\Lib\site-packages\sphinx_theme_builder\__init__.py", line 80, in prepare_metadata_for_build_wheel 
          return _generate_metadata(project, destination=Path(metadata_directory))
        File "C:\Users\Trim21\AppData\Local\Temp\pip-build-env-mz9nqtpo\overlay\Lib\site-packages\sphinx_theme_builder\_internal\distributions.py", line 132, in generate_metadata
          (dist_info / "METADATA").write_text(project.get_metadata_file_contents())
        File "C:\Users\Trim21\scoop\apps\python310\3.10.11\lib\pathlib.py", line 1155, in write_text
          return f.write(data)

```

### CODE REVIEW

**Comment by trim21** [comment]
@pradyunsg hi?

**Comment by trim21** [comment]
@pradyunsg

**Comment by trim21** [comment]
@pradyunsg can you take a look?

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
Apologies for not looking at this sooner, and thanks for the pings! :)

**Comment by neongreen** [comment]
@pradyunsg can this be pushed into a PyPi release? Thanks!

**Pull request merged**
