### PR TITLE
Fix filepaths and use underscores

### PR DESCRIPTION
**Pull request by stevepiercy**
Using dashes in a directory that Sphinx reads caused me problems, so I went with underscores.

Additionally the path names were incorrect and mismatched against the name of the project.

This PR corrects both issues.

### CODE REVIEW

**Comment by pradyunsg** [comment]
> Using dashes in a directory that Sphinx reads caused me problems, so I went with underscores.

Please provide details on the issues you've seen.

**Comment by stevepiercy** [comment]
I cannot reproduce it now, and I did not save the stack trace. I must have had a bad mixture of `-` and `_` somewhere. Then I changed all names to use `_`, and the problems went away. I then changed just the webpack and JavaScript paths to use `-`, and it works fine now.

I'll push a commit to revert that part, but the other part still needs fixing.

**Comment by stevepiercy** [comment]
Commit pushed.

BTW, I'm writing up docs for how to create a sub-theme, some of which might be useful for SBT docs. Additionally my docs will guide me when I create a cookiecutter to generate a project with our theme for documentation. I noticed that you had an idea to do something similar with `stb new`.

**Comment by pradyunsg** [comment]
Thanks @stevepiercy - yea, a PR to the template repository would be great.

**Comment by pradyunsg** [comment]
Bah, it's still a non-existent repository; sorry about that. A pointer to your docs/template would be appreciated!

**Comment by stevepiercy** [comment]
I'll open a new issue, as soon as I publish the docs, as well as the theme as a PyPI package. Then we can see which docs, if any, can be ported to STB.

The cookiecutter will take me a while longer, and will be in a separate repo under the Plone GitHub organization.

**Pull request merged**
