### PR TITLE
expose re-ignore in stb serve

### PR DESCRIPTION
**Pull request by drammock**
This exposes `--re-ignore` as a CLI option for `stb serve`. The "help" text is a bit clunky so please feel free to suggest edits to that.  I was unsure how/where to add a related test, since `tests/workflow/test_serve.py` is an empty file, I didn't have anything to copy/modify :)

xrefs
- https://github.com/pydata/pydata-sphinx-theme/pull/1256
- https://github.com/pydata/pydata-sphinx-theme/pull/1265

### CODE REVIEW

**Comment by drammock** [comment]
friendly bump :)  getting this would really help on pydata-sphinx-theme development, as currently `stb-serve` rebuilds over and over in an infinite loop even when no manual changes are made to the source files.

**Comment by drammock** [comment]
(note also that this resolves the issue @choldgraf mentioned in #24)

**Comment by drammock** [comment]
@pradyunsg Sorry to bump again, but some folks at the [Scientific Python Developer Summit](https://scientific-python.org/summits/developer/2023/) are pestering me about this. Any chance to review soon? cc @munkm @ivanov

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
Hi hi! I've been travelling around, and largely been away from OSS since PyCon basically. :)

**Comment by pradyunsg** [comment]
Of course this doesn't have CI. Well, something for a weekend in the future. :)

**Comment by drammock** [comment]
Thanks! 🎉

**Pull request merged**
