### PR TITLE
Correctly encode RECORD hashes

### PR DESCRIPTION
**Pull request by dlqqq**
# Description

Port of the changes in https://github.com/pypa/installer/pull/141 to STB. Fixes hashes in built wheel `RECORD` files by correcting the hashing procedure to conform to PEP 376 specifications.

# Verification

1. Checkout this branch locally, bump the minor version in `src/sphinx_theme_builder/__init__.py::__version__`, and run `pip install -e .` from the `sphinx-theme-builder` repository root.

2. Clone https://github.com/pydata/pydata-sphinx-theme

3. Run `python -m build --no-isolation` from the `pydata-sphinx-theme` repository root

4. Run this script from the `pydata-sphinx-theme` repository root and verify it does not except:

```
import os
from installer.sources import WheelFile

WHEEL_RELPATH = 'dist/pydata_sphinx_theme-0.13.2.dev0-py3-none-any.whl'

wheel_abspath = os.path.join(os.path.dirname(__file__), WHEEL_RELPATH)

with WheelFile.open(wheel_abspath) as source:
    source.validate_record()
```

# Next steps

This is an upstream transitive dependency of [LangChain](https://github.com/hwchase17/langchain) and [Jupyter AI](https://github.com/jupyterlab/jupyter-ai), which are significant community efforts. A release should quickly follow upon merge.

### CODE REVIEW

**Comment by dlqqq** [comment]
There should also be unit tests to validate this behavior, but that should not block this PR from being merged.

**Comment by pradyunsg** [comment]
Thanks @dlqqq! I literally had a patch for this yesterday evening, but this is good-enough. :)

**Comment by dlqqq** [comment]
@pradyunsg Anything blocking a `0.2.0b2/0.3.0` release today?

**Comment by pradyunsg** [comment]
The lack of free time on my end. I'll try to find some. :)

**Comment by dlqqq** [comment]
@pradyunsg I understand you're busy, but do you think you could spare 10 minutes today to cut a release? Again, this is a transitive dependency of a lot of other projects in the Python ecosystem, so quick action would be appreciated 🤗 

I can assist in this as well, but I'm not sure if you're comfortable with assigning me any privileges as a first-time contributor.

**Comment by dlqqq** [comment]
@pradyunsg ^?

**Pull request merged**
